question_data = [
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    },
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Windows NT&quot; is a monolithic kernel.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Time on Computers is measured via the EPOX System.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first dual-core CPU was the Intel Pentium D.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "A Boolean value of &quot;0&quot; represents which of these words?",
     "correct_answer": "False", "incorrect_answers": ["True"]}
    # {"text": "A slug's blood is green.", "answer": "True"},
    # {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    # {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    # {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    # {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
    #          "you are free to take it home to eat.", "answer": "True"},
    # {"text": "In London, UK, if you happen to die in the House of Parliament, "
    #          "you are entitled to a state funeral.", "answer": "False"},
    # {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    # {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    # {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    # {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    # {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    # {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}

]
